### ISSUE TITLE
save option doesn't work

### ISSUE THREAD

**Issue by evanthomas** [lukealford/abb-speedtest-cli#5]
It's constructing paths with '\\' instead of '/'. Overriding the output destination doesn't help.

```
$ abb-speedtest --location Melbourne --csv --save
{ Error: EACCES: permission denied, mkdir '/home/evan\Documents\abb-speedtests'
    at Object.fs.mkdirSync (fs.js:885:18)
    at checkFolder (/usr/local/lib/node_modules/abb-speedtest-cli/cli.js:63:8)
    at Command.<anonymous> (/usr/local/lib/node_modules/abb-speedtest-cli/cli.js:26:11)
    at Command.listener (/usr/local/lib/node_modules/abb-speedtest-cli/node_modules/commander/index.js:315:8)
    at emitNone (events.js:106:13)
    at Command.emit (events.js:208:7)
    at Command.parseArgs (/usr/local/lib/node_modules/abb-speedtest-cli/node_modules/commander/index.js:665:12)
    at Command.parse (/usr/local/lib/node_modules/abb-speedtest-cli/node_modules/commander/index.js:474:21)
    at Object.<anonymous> (/usr/local/lib/node_modules/abb-speedtest-cli/cli.js:58:9)
    at Module._compile (module.js:652:30)
  errno: -13,
  code: 'EACCES',
  syscall: 'mkdir',
  path: '/home/evan\\Documents\\abb-speedtests' }
```

**Comment by evanthomas** [comment]
It's only partially fixed. The base directory is now OK but the full path is still wrong.

```
$ abb-speedtest --location Melbourne --csv --save
Saving result default directory: /home/evan/Documents/abb-speedtests
Booting speedtest
Custom server location id: 14670
Running speedtest...
Speedtest complete, parsing results...
The file was succesfully saved! /home/evan/Documents/abb-speedtests\result-1598221259218.csv
evan@mesos2:~$ ls Documents/
 abb-speedtests  'abb-speedtests\result-1598221259218.csv'   MaixPyIDE
```

The EACCESS error was caused by the `\` being treated as an escape character creating a path in /home which, indeed, I don't have access to.

There is also a typo in "succesfully" (should be successfully).

**Comment by lukealford** [comment]
@evanthomas should be all fixed now, completely forgot I had the custom output separator hard set.

**Comment by evanthomas** [comment]
Been there, done that. All good now.
